name = "www-fangyoudaizi-com"
compatibility_date = "2024-01-01"

[build]
command = ""
publish = "."

[build.environment]
NODE_VERSION = "18"

# Simplified redirects to avoid loops
[[redirects]]
from = "/wp-admin/*"
to = "/"
status = 301

[[redirects]]
from = "/wp-login.php*"
to = "/"
status = 301

[[redirects]]
from = "/feed"
to = "/"
status = 301

[[redirects]]
from = "/comments/feed"
to = "/"
status = 301

[[redirects]]
from = "/search/*"
to = "/"
status = 301

[[redirects]]
from = "/xmlrpc.php*"
to = "/"
status = 301

[[redirects]]
from = "/wp-json/*"
to = "/"
status = 301
