name = "www-fangyoudaizi-com"
compatibility_date = "2024-01-01"

[build]
command = ""
publish = "."

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*.htm"
to = "/$1"
status = 301

[[redirects]]
from = "/category/*"
to = "/archives/category/$1"
status = 301

[[redirects]]
from = "/author/*"
to = "/archives/author/$1"
status = 301

[[redirects]]
from = "/wp-admin/*"
to = "/"
status = 301

[[redirects]]
from = "/wp-login.php*"
to = "/"
status = 301
